/*
 * This source file was generated by the Gradle 'init' task
 */
package ticket.booking;

import static org.junit.Assert.*;

import org.junit.Test;

public class AppTest {
    @Test public void appExists() {
        App classUnderTest = new App();
        assertNotNull("app should exist", classUnderTest);
    }
}
