/*
 * This source file was generated by the Gradle 'init' task
 */
package ticket.booking;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.UUID;

import ticket.booking.entities.User;
import ticket.booking.services.UserBookingService;
import ticket.booking.utils.UserServiceUtils;


public class App
{
    public static void main(String[] args)
    {
        System.out.println("Command Line IRCTC");
        Scanner sc = new Scanner(System.in);
        int option = 0;
        UserBookingService userBookingService;
        try
        {
            userBookingService = new UserBookingService();
        }
        catch (IOException e)
        {
           System.out.println("Error: User booking service is not available");
           return;
        }
        while(option!=7)
        {
            System.out.println("Choose Option");
            System.out.println("1. Sign Up");
            System.out.println("2. Sign In");
            System.out.println("3. Fetch Booking Details");
            System.out.println("4. Search Trains");
            System.out.println("5. Book a Seat");
            System.out.println("6. Cancel Booking");
            System.out.println("7. Sign Out & Exit");

            option = sc.nextInt();
            switch(option)
            {
                case 1:
                    sc.nextLine(); // consume the newline left by nextInt()
                    System.out.println("Enter Your Username");
                    String usernameToSignUp = sc.nextLine();
                    System.out.println("Enter Your Name");
                    String nameToSignUp = sc.nextLine();
                    System.out.println("Enter Your Password");
                    String passwordToSignUp = sc.nextLine();
                    System.out.println("Enter Your Email Address");
                    String emailToSignUp = sc.nextLine();
                    System.out.println("Enter Your Phone Number");
                    String phoneToSignUp = sc.nextLine();
                    User user = new User(
                            nameToSignUp,
                            usernameToSignUp,
                            passwordToSignUp,
                            UserServiceUtils.hashPassword(passwordToSignUp),
                            emailToSignUp,
                            phoneToSignUp,
                            new ArrayList<>()                   // empty list of tickets
                    );
                    System.out.println("Your Details are as follows : "+user);
                    userBookingService.signUpUser(user);
                    break;
                    case 2:
                        System.out.println("Login Method");
                        System.out.println("1. Via Phone Number");
                        System.out.println("2. Via Email Address");
                        System.out.println("3. Via Username");
                        String loginMethod = sc.next();
                        if(loginMethod.equals("1"))
                        {
                            System.out.println("Enter Phone Number");
                            String phoneToSignIn = sc.next();
                        }
                        else if(loginMethod.equals("2"))
                        {
                            System.out.println("Enter Email Address");
                            String emailToSignIn = sc.next();
                        }
                        else if(loginMethod.equals("3"))
                        {
                            System.out.println("Enter Username");
                            String usernameToSignIn = sc.next();
                        }
                        else{
                            System.out.println("Wrong Login Method");
                        }
                        System.out.println("Enter Your Password");
                        String passwordToSignIn = sc.next();
                        User usertoSignIn = new User(
                                ,
                                UUID.randomUUID().toString(),        // userId should be UUID
                                passwordToSignIn,
                                UserServiceUtils.hashPassword(passwordToSignIn),
                                emailToSignUp,
                                phone,
                                new ArrayList<>()
                        );


            }
        }
    }
}
